apiVersion: v1
kind: Service
metadata:
  name: {{ include "dsp-svc.fullname" . }}
  labels:
    {{- include "dsp-svc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "dsp-svc.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
