= Developer`s Guide

== Local Workflow

[source,bash]
----
export CMAKE_BUILD_PARALLEL_LEVEL=4
./scripts/install-nova.sh
./scripts/run.sh build
----

== Docker Workflow

Build a Docker image (install Docker Buildx plugin). It contains all the
necessary build tools for building DSP.

// TODO(env): Docker environment is outdated.

// CMD: devenv
[source,bash]
----
docker build ./env -f ./env/buildenv.Dockerfile -t dsp-dev:latest
----

Create a container from the built image. All dependencies are downloaded and
built by Conan. They are not available in the image, so to avoid rebuilding
everything, keep the container.

Ports used by DSP are exposed and the container can reach the host via
`host.docker.internal` in case some service runs directly on the host and not
in another container. It is not necessary to put this container in a docker
network given the other containers are exposed their ports.

// CMD: create-container
[source,bash]
----
docker run -it --name dsp-build --detach \
    --volume "${PWD}":"${PWD}" \
    --workdir "${PWD}" \
    --add-host=host.docker.internal:host-gateway \
    --publish 7200:7200 \
    --publish 9555:9555 \
    dsp-dev \
    /bin/bash
----

Then build DSP code with the custom build wrapper tool, Baldr.

// CMD: build-in-container
[source,bash]
----
docker exec dsp-build \
    baldr \
        --project "${PWD}" \
        --build-type Debug \
        --target all \
        --jobs $(($(nproc) / 2))

docker exec dsp-build \
    baldr \
        --project "${PWD}" \
        --build-type Release \
        --target all \
        --jobs $(($(nproc) / 2))
----

An example service is packaged into its own Docker image. This can be used for
trying out the framework either directly in Docker or it can be deployed into a
Kubernetes cluster.

See `package` and `deploy` stages.

The Helm version uses its own DSP configuration instead of the one in the `res`
directory. Log levels are set to "trace" for the highest level of
observability.

// CMD: run-service-container
[source,bash]
----
docker run --rm \
    --volume "${PWD}"/res:/opt/ystre/etc \
    --env DSP_CONFIG=/opt/ystre/etc/dsp.yaml \
    --env SPDLOG_LEVEL=trace \
    --publish 7200:7200 \
    --name svc \
    local/svc:latest
----

== Profiling

Build Tracy Profiler with the following command.

 baldr -p ./deps/tracy/profiler -b Release -t tracy-profiler -DLEGACY=1

`LEGACY` is used for GLFW instead of Wayland. Wayland seems to have some issues.

Use the following command to build the sandbox with profiling enabled.

 baldr -p . -b Debug -t tracy-sandbox -r -DPROFILING=ON -DMALLOC_PROFILING=ON

Disable callstacks for improving the performance a bit.

 baldr -p . -b Debug -t tracy-sandbox -r -DPROFILING=ON -DMALLOC_PROFILING=ON -DPROFILING_CALLSTACK_DEPTH=0
