= Environment setup

NOTE: All commands assume the root of the project as working directory.

The purpose is to provide an enviroment for various runtime testing.

== Docker

The following command creates Docker containers for the necessary dependencies.

// CMD: setup
[source,bash]
----
docker compose -f ./env/docker-compose.yml up -d
----

=== Important ports

[cols="2,1"]
|===
| Name | Port
| Grafana | 3000
| Prometheus Server | 9090
| DSP Southbound | 7200
| DSP Prometheus Scrape | 9555
| RedPanda Console | 8080
| RedPanda Kafka API | 19092
|===

=== Resources

Kafka can be rate limited via the following command (empty string resets the
property to its default value). Resources are set to 1 CPU and 4GB memory.

// CMD: kafka-rate-limit
[source,bash]
----
docker exec -it redpanda-0 rpk cluster config set kafka_throughput_limit_node_in_bps=""
----

== Kubernetes

_Coming Soon_

== Metrics

The following dashboard is a good starting place to monitor the system
enviroment during performance testing.

https://grafana.com/grafana/dashboards/1860-node-exporter-full/

DSP dashboard is saved in `res/grafana-dashboard-dsp.json`.
